import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Libre_Caslon_Text } from "next/font/google";
import { AppConfig } from "@/utils/config";
import Preloader from "@/components/Preloader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const libreCaslonText = Libre_Caslon_Text({
  variable: "--font-libre-caslon-text",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${libreCaslonText.variable} antialiased`}
      >
        <Preloader dev={AppConfig.preloader.dev}/>
        {children}
      </body>
    </html>
  );
}
